### ISSUE TITLE
Exception and ctrl-c

### ISSUE THREAD

**Issue by kasperdokter** [wanth1997/python-wootrade#6]
If you set in the websocket demo code in the readme the wsm to deamon via `wsm.setDaemon(True)`, then it shows the following:

`start_socket() got an unexpected keyword argument 'conn_name'`

The reason I tried this, is because I want to shut the app down with ctrl-c. The fix is the correct the parameter in the private connection.

A second issue is that I got the code running only for testnet=False. You might want to update this too, or provide instructions to get the code working with testnet=True.

**Comment by wanth1997** [comment]
Ohhh! Thx for pointing this out.
There's some Inconsistency between my sample code and package.
Already fixed in latest version.!
