### ISSUE TITLE
How to subscribe to order cancel events on websocket in Woo exchange api

### ISSUE THREAD

**Issue by saurabh-rajput** [wanth1997/python-wootrade#7]

**Comment by saurabh-rajput** [comment]
Could not find the subscription request to subscibe to order cancel messages on websocket. Kindly let me know if you know anything on this front

**Comment by wanth1997** [comment]
Sorry for late reply, some new added endpoint aren't being added to my sdk yet.
However, you can still subscribe them by using `subscribe` function directly.

Check this out https://github.com/wanth1997/python-wootrade/blob/main/wootrade/streams.py#L326
